### PR TITLE
Remove text

### PR DESCRIPTION
**Pull request by markjmeredith**
That bit about assigning access to more than one resource at a time through a resource group isn't true. IAM policies don't cascade, unless something has changed recently.

### CODE REVIEW

**Comment by mekaufman** [comment]
@markjmeredith You can assign a policy on all identity and access enabled services that exist in the selected RG, so I think it is correct:

image

**Comment by markjmeredith** [comment]
That's not true. Those are two different policies, one for the RG itself, and one for a specific set of services. Those are not causally related.

**Comment by mekaufman** [comment]
@markjmeredith Ok, I feel like I'm missing something here though. I get what you're saying they are definitely not related and are two separate policies. I completely agree.

However, the ability to assign someone access to more than one resource by assigning access to all resources in a RG is possible though which is what that doc is stating as a benefit. Because I thought the best practice and benefit of organizing resources in RGs was to organize a set that you want to give a user or users access to all at once to make assigning policies easier by assigning a minimum amount. So, between RGs and access groups now, you could organize 5 devs who all need access to 5 instances within 1 group and just set the one policy (which does result in two if you give them access to the group...). With all that said, maybe that statement doesn't belong where it is today in this topic as part of the definition of the RG, but I still think it is a true statement.

**Comment by markjmeredith** [comment]
I talked more with Nancy about this for my own understanding. I was wrong! If you set both of those policies you end up with access scoped to an RG. You're right!

**Pull request closed without merging**
